### PR TITLE
Updated to support Swift 2

### PR DESCRIPTION
**Pull request by tie**

### CODE REVIEW

**Comment by tie** [comment]
Hm, looks like `swift-2.0` branch travis build needs an update.

 `–  osx_image: xcode6.4`
 `+  osx_image: xcode7.1`

**Comment by tie** [comment]
Also, I am woking on full Swift 2.0 version of your project

**Comment by kostiakoval** [comment]
Wow, thanks for the contribution! :tada: :+1:

**Comment by tie** [comment]
Finished working on major Swift 2 changes.
With Swift 2 previous features of Mirror framework would be 'overdoing their job', because most of them are available by default in `Mirror` from Standard Library.

Updated the README.md, so the users would know how to use `Mirror` from `stdlib` with extension from framework.

Commented out computed property `memorySize` in implementation and tests for now.
There are still a few things that need to be updated/fixed/implemented.

**Comment by kostiakoval** [comment]
Great PR, review it now

**Comment by tie** [comment]
Thank you for merging :tada: 

By the way, I've just found my mistake in `README.md`:

```
let mirP = mirror.children[index.successor()]
```

instead of:

```
var mirP = mirror[index.successor()]
```

**Comment by kostiakoval** [comment]
can you PR? you can do it directly form gihub, just edit the readme file :)

**Comment by kostiakoval** [comment]
But you have removed most of the functionality of the Mirror? why?

**Comment by tie** [comment]
1. Most of the old functionality is provided with Swift's Standard Library.
2. Converting Type to String is not a good idea. It could be implemented with only one line of code, so I am just letting the user handle it. Also, it saves your time because no more problems like that one #3 (they will go to stackoverflow.com and ask/find a question/answer)
3. To provide previous functionality related to reflected object (like `memorySize`) the implementation wrapper object is needed (afaik, there is no public API for getting reflected object from `Mirror`).

There is one possible alternative:

```
public (protocol or struct) Reflector<T> {
    public internal(set) var mirror: Mirror // { get }
    public internal(set) var reflected: T  // { get }

    // most of the functionality of the previous Mirror
    // and additional ObjC runtime methods (using macros for version w/ or w/o objc runtime)
}

let object = <#....#>
let reflected = Reflector(reflecting: object)
reflected.____           // accessing additional
reflected.mirror.____ // accessing Mirror
```

This approach gives us an easy-to-modify implementation, where we can add as much of old functionality as required and some `ObjC` runtime dependent code.
But, anyway, the `Mirror` extensions should be included in (pseudo-)code above to keep an API simple and clear.

**Comment by tie** [comment]
Oh, and converting to NSDictionary also could be done by user (from `Dictionary<String, AnyObject>` to `NSDictionary`, as simple as `nativeDict as NSDictionary`)

**Pull request merged**
